create table if not exists users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null,
    email    varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists posts
(
    id         bigint generated by default as identity primary key,
    user_id    bigint references users (id) on delete cascade,
    title      varchar(255) not null,
    image_path varchar(512),
    content    clob         not null,
    created_at timestamp    not null default current_timestamp,
    updated_at timestamp
);
create table if not exists likes
(
    id      bigint generated by default as identity primary key,
    user_id bigint references users (id) on delete cascade,
    post_id bigint references posts (id) on delete cascade,
    constraint uq_likes_user_post unique (user_id, post_id)
);

create table if not exists comments
(
    id         bigint generated by default as identity primary key,
    user_id    bigint references users (id) on delete cascade,
    post_id    bigint references posts (id) on delete cascade,
    content    clob      not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp
);


